C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)
C     
      SUBROUTINE FFV2_2(F1, V3, COUP, M2, W2,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(6)
      COMPLEX*16 V3(*)
      REAL*8 P2(0:3)
      REAL*8 W2
      COMPLEX*16 F1(*)
      REAL*8 M2
      COMPLEX*16 DENOM
      COMPLEX*16 COUP
      F2(1) = +F1(1)+V3(1)
      F2(2) = +F1(2)+V3(2)
      P2(0) = -DBLE(F2(1))
      P2(1) = -DBLE(F2(2))
      P2(2) = -DIMAG(F2(2))
      P2(3) = -DIMAG(F2(1))
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      F2(3)= DENOM*CI * V3(3)*(F1(5)*(P2(0)-P2(3))+(F1(6)*(+CI*(P2(2))
     $ -P2(1))+F1(3)*M2))
      F2(4)= DENOM*(-CI )* V3(3)*(F1(5)*(P2(1)+CI*(P2(2)))+(F1(6)*(
     $ -1D0)*(P2(0)+P2(3))-F1(4)*M2))
      F2(5)= DENOM*(-CI )* V3(3)*(F1(3)*(-1D0)*(P2(0)+P2(3))+(F1(4)*(
     $ +CI*(P2(2))-P2(1))-F1(5)*M2))
      F2(6)= DENOM*CI * V3(3)*(F1(3)*(P2(1)+CI*(P2(2)))+(F1(4)*(P2(0)
     $ -P2(3))+F1(6)*M2))
      F2(7)= DENOM*CI * V3(4)*(F1(5)*(P2(0)-P2(3))+(F1(6)*(+CI*(P2(2))
     $ -P2(1))+F1(3)*M2))
      F2(8)= DENOM*(-CI )* V3(4)*(F1(5)*(P2(1)+CI*(P2(2)))+(F1(6)*(
     $ -1D0)*(P2(0)+P2(3))-F1(4)*M2))
      F2(9)= DENOM*(-CI )* V3(4)*(F1(3)*(-1D0)*(P2(0)+P2(3))+(F1(4)*(
     $ +CI*(P2(2))-P2(1))-F1(5)*M2))
      F2(10)= DENOM*CI * V3(4)*(F1(3)*(P2(1)+CI*(P2(2)))+(F1(4)*(P2(0)
     $ -P2(3))+F1(6)*M2))
      F2(11)= DENOM*CI * V3(5)*(F1(5)*(P2(0)-P2(3))+(F1(6)*(+CI*(P2(2))
     $ -P2(1))+F1(3)*M2))
      F2(12)= DENOM*(-CI )* V3(5)*(F1(5)*(P2(1)+CI*(P2(2)))+(F1(6)*(
     $ -1D0)*(P2(0)+P2(3))-F1(4)*M2))
      F2(13)= DENOM*(-CI )* V3(5)*(F1(3)*(-1D0)*(P2(0)+P2(3))+(F1(4)*(
     $ +CI*(P2(2))-P2(1))-F1(5)*M2))
      F2(14)= DENOM*CI * V3(5)*(F1(3)*(P2(1)+CI*(P2(2)))+(F1(4)*(P2(0)
     $ -P2(3))+F1(6)*M2))
      F2(15)= DENOM*CI * V3(6)*(F1(5)*(P2(0)-P2(3))+(F1(6)*(+CI*(P2(2))
     $ -P2(1))+F1(3)*M2))
      F2(16)= DENOM*(-CI )* V3(6)*(F1(5)*(P2(1)+CI*(P2(2)))+(F1(6)*(
     $ -1D0)*(P2(0)+P2(3))-F1(4)*M2))
      F2(17)= DENOM*(-CI )* V3(6)*(F1(3)*(-1D0)*(P2(0)+P2(3))+(F1(4)*(
     $ +CI*(P2(2))-P2(1))-F1(5)*M2))
      F2(18)= DENOM*CI * V3(6)*(F1(3)*(P2(1)+CI*(P2(2)))+(F1(4)*(P2(0)
     $ -P2(3))+F1(6)*M2))
      END


