ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Scalar_U_v3_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_111 = ', GC_111
      WRITE(*,2) 'GC_115 = ', GC_115
      WRITE(*,2) 'GC_13 = ', GC_13
