ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Scalar_U_v2_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_82 = ', GC_82
      WRITE(*,2) 'GC_102 = ', GC_102
      WRITE(*,2) 'GC_115 = ', GC_115
      WRITE(*,2) 'GC_120 = ', GC_120
      WRITE(*,2) 'GC_13 = ', GC_13
