ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of sm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_51 = ', GC_51
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_59 = ', GC_59
      WRITE(*,2) 'GC_100 = ', GC_100
