ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Scalar_U_v3_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_75 = ', GC_75
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_80 = ', GC_80
      WRITE(*,2) 'GC_81 = ', GC_81
      WRITE(*,2) 'GC_101 = ', GC_101
      WRITE(*,2) 'GC_104 = ', GC_104
      WRITE(*,2) 'GC_107 = ', GC_107
      WRITE(*,2) 'GC_111 = ', GC_111
      WRITE(*,2) 'GC_115 = ', GC_115
      WRITE(*,2) 'GC_117 = ', GC_117
      WRITE(*,2) 'GC_124 = ', GC_124
      WRITE(*,2) 'GC_13 = ', GC_13
